language: node_js

node_js:
  - 4.2.0
  - 5.4.0

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget http://deepin.mirror.garr.it/mirrors/deepin/pool/non-free/g/google-chrome-stable/google-chrome-stable_47.0.2526.80-1_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - npm install semver
  - export NPM_V=$(npm -v)
  - 'if node -e "process.exit(require(''semver'').gt(process.env.NPM_V, ''3.0.0''))"; then npm install -g npm@3.0.0; fi'

install:
  - npm install

before_script:
  - "npm run webdriver:start &"

script:
  - npm run lint

  - npm start
  - npm run unit
  - npm stop

  - "kill $(lsof -t -i:3000) | true"

  - NG2_WW=true  NG2_SS=true  $(npm bin)/pm2 start ecosystem.json
  - npm run e2e
  - $(npm bin)/pm2 delete ecosystem.json;

  - "kill $(lsof -t -i:3000) | true"

  - NG2_WW=false NG2_SS=true  $(npm bin)/pm2 start ecosystem.json
  - npm run e2e
  - $(npm bin)/pm2 delete ecosystem.json;

  - "kill $(lsof -t -i:3000) | true"

  - NG2_WW=false NG2_SS=false $(npm bin)/pm2 start ecosystem.json
  - npm run e2e
  - $(npm bin)/pm2 delete ecosystem.json;

  - "kill $(lsof -t -i:3000) | true"

  - "NG2_WW=true NG2_SS=true npm run dev &"
  - DEV_SERVER_PID=$!
  - sleep 5
  - npm run e2e
  - kill $DEV_SERVER_PID

  - "kill $(lsof -t -i:3000) | true"

  - "NG2_WW=false NG2_SS=true npm run dev &"
  - DEV_SERVER_PID=$!
  - sleep 5
  - npm run e2e
  - kill $DEV_SERVER_PID

  - "kill $(lsof -t -i:3000) | true"

  - "NG2_WW=false NG2_SS=false npm run dev &"
  - DEV_SERVER_PID=$!
  - sleep 5
  - npm run e2e
  - kill $DEV_SERVER_PID

  - "kill $(lsof -t -i:3000) | true"

  - npm restart
  - npm test
  - npm stop
